### ISSUE TITLE
kbutils.py has no function bytearray_to_bytes

### ISSUE THREAD

**Issue by Eofric** [virtualabs/cc2531-killerbee-fw#3]
Firstly, thank you very much for this project.  I have used the Atmel RAVEN USBSTICK in the past, but that is no longer available and my students have 'borrowed' all but one of my remaining devices.  If I can get this working, it will be a God send.
I have managed to flash a CC2531 (via a Pi) and have made all the edits to Killerbee python scripts in your pull request so that the device is now picked up by zbid.  However, when I try to run zbstumbler or zbwireshark, I get the error (originating from dev_bumblebee.py):

ImportError: cannot import name bytearray_to_bytes

and sure enough, looking through kbutils.py, I cannot see a definition for that function.

**Comment by virtualabs** [comment]
Well, thank you for giving Bumblebee a try ! 

First, this issue relates to another repository (my killerbee repository I guess) so you'd better post an issue in this project rather than this one (which is actually about the Bumblebee firmware and not killerbee itself). Second, you have to checkout the `py` branch of my killerbee repository rather than sticking with the `master` branch, as my pull request only concerns killerbee's python3-compatible branch (because python2 is deprecated). 

I hope it will solve your problem !

**Comment by Eofric** [comment]
Thank you very much for your reply, which makes absolute sense.

I hadn’t seen your killerbee repo. I was using riverloopsec’s and had edited the files in my downloaded copy to reflect the changes in your pull request on that site. 

I will give your py3 branch a road test.
